# Generated by Django 3.0.7 on 2020-08-09 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='customer/')),
                ('contact', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pno', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderdate', models.DateField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.CustomerModel')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.ProductModel')),
            ],
        ),
    ]
